### ISSUE TITLE
Visualbundle往bin保存.dat64是saving 1/2滑鼠轉圈圈議會后整個程序崩潰消失。

### ISSUE THREAD

**Issue by Acer-bdog** [aianlinb/LibBundle#10]
Visualbundle往bin替換保存.dat64時saving 1/2滑鼠轉圈圈議會后整個程序崩潰消失，查看bin文檔修改日期，發現_.index.bin修改時間未改變，而想要修改替換的.bin檔最後修改時間變成了Visualbundle崩潰消失的時間。
有時.dat64檔能保存進bin，放進GGPK后進游戲後游戲整個消失，pathofexile64.exe進程都不見了。

**Comment by aianlinb** [comment]
Please restore the backup first and try again with the latest version of VisualBundle and VisualGGPK
請先還原備份後使用最新版的 VisualBundle 和 VisualGGPK 再試一次
https://github.com/aianlinb/LibBundle/releases
https://github.com/aianlinb/libggpk/releases

**Comment by Acer-bdog** [comment]
謝謝大大，我已經下載試了最新的1.3，還是Visualbundle會在1/2的時候轉圈消失，_.index.bin修改時間未改變，和v1.2一樣的情況

**Comment by Acer-bdog** [comment]
我又嘗試用同名.dat64的替換同名的.dat的檔，可以成功替換保存，_.index.bin修改時間也變了，但是這個我也知道進游戲肯定是會報錯崩潰的(●ˇ∀ˇ●)

**Comment by aianlinb** [comment]
直接消失沒有出現錯誤視窗嗎?

**Comment by Acer-bdog** [comment]
沒有錯誤視窗，直接消失

**Comment by Acer-bdog** [comment]
我剛才想既然替換不行，在巴哈上看到大大說：
AddFiles 加入檔案至所選的bundle，只能加入GGPK中已經存在的檔案，可以不在目前有讀取到的bundle沒關係，加入後路徑會直接指向新檔案(透過修改_.index.bin)，丟回GGPK後舊的檔案就不會被讀取。

我就想用AddFiles功能加入吧，比如AddFiles加入AchievementItemRewards.dat64，但是彈出錯誤說沒有建立索引，不能加入
---------------------------
Error
---------------------------
The index didn't define the file:

AchievementItemRewards.dat64
---------------------------
確定   
---------------------------

**Comment by aianlinb** [comment]
Addfiles必須選擇一個資料夾
選擇方式: 進入那個資料夾後直接按開啟
程式會把那個資料夾內所有檔案都加入
你的檔案都要照著原本的相對路徑放
例如你那個檔案是在Data資料夾底下
你就要這樣放:
ABC/Data/AchievementItemRewards.dat64
然後進入ABC按開啟按鈕

**Comment by Acer-bdog** [comment]
> Addfiles必須選擇一個資料夾
> 選擇方式: 進入那個資料夾後直接按開啟
> 程式會把那個資料夾內所有檔案都加入
> 你的檔案都要照著原本的相對路徑放
> 例如你那個檔案是在Data資料夾底下
> 你就要這樣放:
> ABC/Data/AchievementItemRewards.dat64
> 然後進入ABC按開啟按鈕

我按大大説的方法試了，可以加入，但是出現了問題，我把我要加入的dat64檔放入Data.bundle.bin,加入進去了，但是加入以後，Data.bundle.bin從剛導出來的21KB變成了1kB,用Visualbundle再次打開_.index.bin，能看到Data.bundle.bin裏有我加入的文檔，但是打開裏面都是空白的沒有内容

**Comment by Acer-bdog** [comment]
> > Addfiles必須選擇一個資料夾
> > 選擇方式: 進入那個資料夾後直接按開啟
> > 程式會把那個資料夾內所有檔案都加入
> > 你的檔案都要照著原本的相對路徑放
> > 例如你那個檔案是在Data資料夾底下
> > 你就要這樣放:
> > ABC/Data/AchievementItemRewards.dat64
> > 然後進入ABC按開啟按鈕
> 
> 我按大大説的方法試了，可以加入，但是出現了問題，我把我要加入的dat64檔放入Data.bundle.bin,加入進去了，但是加入以後，Data.bundle.bin從剛導出來的21KB變成了1kB,用Visualbundle再次打開_.index.bin，能看到Data.bundle.bin裏有我加入的文檔，但是打開裏面都是空白的沒有内容

**Comment by Acer-bdog** [comment]
我剛才不小心按錯了，關閉了這個問題，不知道大大還能看到不，沒用過github,
我補充一下，我還在

> > > Addfiles必须选择一个资料夹
> > > 选择方式：进入那个资料夹后直接按开启
> > > 程序会把那个资料夹内所有档案都加入
> > > 你的档案都要照着原本的相对路径放
> > > 例如你那个档案是在Data资料夹底下
> > > 你就要这样放：
> > > ABC / Data / AchievementItemRewards.dat64 
> > > 然后进入ABC按开启按钮
> > 
> > 
> > 我按大大说的方法试了，可以加入，但是出现了问题，我把我要加入的dat64档放入Data.bundle.bin，加入进去了，但是加入以后，Data.bundle.bin从刚导出来的21KB变成了1kB，用Visualbundle再次打开__。index.bin，能看到Data.bundle.bin里有我加入的文档，但是打开里面都是空白的没有内容

我剛才按錯了關閉了這個Iss,我補充一下上面的，我還往Data.bundle.bin放入了.txt文檔，裏面是有文字的，Addfiles以後再次打開就沒有文字内容了，再次導出那個文檔，占用的空間大小還是和原來一樣，比如原來.txt大小是23K，放入Data.bundle.bin裏顯示也是23k,導出後大小還是和原來一樣23k,但是裏面的文字内容消失了。
我原來Addfiles進去的Data文件夾有34MB大小，但是進去以後變1KB，剛開始看到Data.bundle.bin的大小我還在想這是什麽壓縮技術這麽先進呢(●ˇ∀ˇ●)

**Comment by aianlinb** [comment]
我照著做也跟你一樣，我正在找出問題

**Comment by Acer-bdog** [comment]
> 我照著做也跟你一樣，我正在找出問題

大大倖苦了。
我剛才嘗試只Addfiles一個11k的txt文檔，Data.bundle.bin大小倒是沒變1k,還是原始導出的23K，但是文檔裏的文字也是同樣的消失了。可能不是因爲要加入進去的檔案太大的關係。

**Comment by aianlinb** [comment]
已修復 https://github.com/aianlinb/LibBundle/commit/1d66b19cd9cb7604ae08af012ff855e5cdf2211b
請下載最新版重試

**Comment by Acer-bdog** [comment]
謝謝大大，我用替換的方法替換.dat64后進游戲，游戲會閃退崩潰，用Addfiles文件夾的方式，目前進游戲5分鐘了，一切正常。
大大辛苦了。

**Comment by aianlinb** [comment]
@Acer-bdog 今天又修復了一個重大錯誤，建議你還原備份後用最新版程式重改一次
