### ISSUE TITLE
UISetting.xml 未在 _index 中定义问题

### ISSUE THREAD

**Issue by wycaca** [aianlinb/LibBundle#11]
使用 AddFiles功能添加 `Metadata\UI\UISettings.xml` 会提示_index未定义
导出的文件列表中确实不存在该文件
但是使用bun_extract_file.exe 可以成功解压这个文件 
[https://github.com/zao/ooz](url)
cmd 解压命令, 如下:
`bun_extract_file  extract-files "%POE_Path%" .  Metadata/UI/UISettings.xml`

另外, 雕像大的补丁已经成功修改字体, 添加了该文件, 提取雕像大补丁的文件结构也未发现这个文件
是不是这个文件的存放信息比较特殊? 请问可以解决一下这个问题吗? 
谢谢

**Comment by aianlinb** [comment]
Fixed https://github.com/aianlinb/LibBundle/commit/5a07d8e41d00b7c4e597f6bdcdcdc5c137a3f0d9 in Beta v1.5
