### ISSUE TITLE
Missing Class File

### ISSUE THREAD

**Issue by wycaca** [aianlinb/LibBundle#13]
Please upload OpenFolderDialog class.
![image](https://user-images.githubusercontent.com/12526730/95776811-a0d98f00-0cf7-11eb-9e6a-c380aea5cbe6.png)

**Comment by aianlinb** [comment]
Fixed https://github.com/aianlinb/LibBundle/commit/14af5078effa3bb9202f27c0a7270a6dd38f0d24
