### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by Siblingvv** [aianlinb/LibBundle#2]
![изображение](https://user-images.githubusercontent.com/6499619/94143685-d87fb480-fe78-11ea-93d7-57c805c32161.png)

On start, when i opened index.bin

"Invalid parametr"
memory loaded on 546 mb

**Comment by aianlinb** [comment]
Working on.
Please don't load too many bundle.bin at the same time for now.

**Comment by Siblingvv** [comment]
And if i extracted EnvironmentSettings by BundleExpoter - he extract 1000+ files.
But VisualBundle extracts only 250+

**Comment by aianlinb** [comment]
@Siblingvv Are you sure you put all the bundle.bin that contains "EnvironmentSettings" at relative path?
By the way, the BundleExpoter will export all the file in all the bundle.bin it found, may not only files in EnvironmentSettings.

**Comment by Siblingvv** [comment]
I cannot verify this completely while there is a problem with System.ArgumentException
