### ISSUE TITLE
addFiles Path issues

### ISSUE THREAD

**Issue by wycaca** [aianlinb/LibBundle#3]
In the OnButtonAddClick funcation, https://github.com/aianlinb/LibBundle/blob/41bfc1ba47ed392c5c42f8167f328b65de6ae83f/VisualBundle/MainWindow.xaml.cs#L307 
and https://github.com/aianlinb/LibBundle/blob/41bfc1ba47ed392c5c42f8167f328b65de6ae83f/VisualBundle/MainWindow.xaml.cs#L316

the path should keep the last folder name, can be modified with this:

`var path = f.Remove(0, fbd.SelectedPath.LastIndexOf("\\")).Replace("\\","/");`

**Comment by aianlinb** [comment]
IndexContainer.Hashes.Values contains "path".
And the filename hash also need the full path.
So we need the full path but not only the file name.
