### ISSUE TITLE
freeze on opening  _tiny_1.bundle.bin due to GUI performance

### ISSUE THREAD

**Issue by Nathan8489** [aianlinb/LibBundle#4]
too many files inside this bundle, TreeView get messed up.

雖然沒學過WPF，不過我試著研究一下。

**Comment by aianlinb** [comment]
The same problem: https://github.com/aianlinb/LibBundle/issues/2

**Comment by Nathan8489** [comment]
Opening it within a few seconds, but needs re-implement others function interactive with TreeView since I change its Struction (basically every function).
Also fixed the issue: #2 

![image](https://user-images.githubusercontent.com/6212839/94294607-a5314880-ff92-11ea-8652-8c5edcc67c27.png)
