### ISSUE TITLE
[Feature Request] Replace all files in loaded bundle

### ISSUE THREAD

**Issue by Nathan8489** [aianlinb/LibBundle#7]
There are thousands of texture separated to hundreds bundle, replace they manually will kill my sanity.

**Comment by aianlinb** [comment]
You can just use the button "Addfiles" to put it in any bundle.bin.
That will replace all files you added. (but it won't delete the old files)

**Comment by aianlinb** [comment]
https://github.com/aianlinb/LibBundle/commit/b4064cf2e1f5ec337c0be5af767cf1cc04530b8e

**Comment by Siblingvv** [comment]
> 
> 
> You can just use the button "Addfiles" to put it in any bundle.bin.
> That will replace all files you added. (but it won't delete the old files)

but if u use this button u can use only one file, not multiple

**Comment by aianlinb** [comment]
@Siblingvv You reminded me that I forgot to allow multiple selections

**Comment by aianlinb** [comment]
@Siblingvv Not true, it will select the folder, not the file.

**Comment by Siblingvv** [comment]
> 
> 
> @Siblingvv Not true, it will select the folder, not the file.

sorry, my mistake
