### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Siblingvv** [aianlinb/LibBundle#8]
![изображение](https://user-images.githubusercontent.com/6499619/94337352-7ba80980-fff2-11ea-9b88-1d9e32c08fa1.png)
![изображение](https://user-images.githubusercontent.com/6499619/94337373-9da18c00-fff2-11ea-9627-699085fec686.png)

Missing files in a project

**Comment by aianlinb** [comment]
Fixed https://github.com/aianlinb/LibBundle/commit/44d2d4e4f7a24e874dc5b7530c4f4cdc00eed06d
